= Development resources
Cyrille Chopelet <cyrille.chopelet@mines-nancy.org>

// Github, Travis, Waffle/issues & license
:github-user: cyChop
:github-repo: dev-resources
:github-description: Resources for KP's Github hosted projects.
:travis-built: false
:waffle: {github-repo}
:license-name: MIT
:license-url: http://opensource.org/licenses/MIT
// Maven projects
//:pom-groupid: org.keyboardplaying
//:pom-artifactid: {github-repo}
// Sonar projects
//:sonar-groupid: {pom-groupid}
//:sonar-artifactid: {pom-artifactid}
// The badges. Should not require any change.
:url-shields: http://img.shields.io/
:url-sonar: sonar.keyboardplaying.org
// Travis
ifeval::["{travis-built}" == "true"]
image:{url-shields}travis/{github-user}/{github-repo}/master.svg?style=plastic[Build status, link="https://travis-ci.org/{github-user}/{github-repo}"]
endif::[]
// Sonar badges
ifdef::sonar-groupid,sonar-artifactid[]
image:{url-shields}sonar/http/{url-sonar}/{sonar-groupid}:{sonar-artifactid}/coverage.svg?style=plastic[Test coverage, link="http://{url-sonar}/drilldown/measures/?id={sonar-groupid}:{sonar-artifactid}&metric=coverage"]
image:{url-shields}sonar/http/{url-sonar}/{sonar-groupid}:{sonar-artifactid}/tech_debt.svg?style=plastic[Technical debt, link="http://{url-sonar}/dashboard/index?id={sonar-groupid}:{sonar-artifactid}"]
endif::sonar-groupid,sonar-artifactid[]
// Waffle
ifdef::waffle[]
image:https://badge.waffle.io/{github-user}/{waffle}.svg?label=ready&title=Ready[Waffle, link="https://waffle.io/{github-user}/{waffle}"]
endif::waffle[]
// License
//image:{url-shields}github/license/{github-user}/{github-repo}.svg?style=plastic[License: {license-name}, link="{license-url}"]

This repository contains some standard settings or template files that help me streamline my developments.

The templates and settings were designed for my own use but feel free to use and tailor it to your own requirements.
I advise using the Eclipse settins here if you wish to contribute to one of my projects.

Additional documentation may be found in each directory.

[cols="1,3", options="header"]
|===
| Directory          | Description

| `github-templates` | Standard files that can be applied to most Github projects

| `maven-templates`  | Template files for Maven (POM)

| `java-source`      | Reusable classes

| `eclipse-settings` | Eclipse settings to be used when creating a new workspace
|===
