= github-hosted-maven-kp-project
Cyrille Chopelet <cyrille.chopelet@mines-nancy.org>

This directory contains several POMs which can be used as bases when creating a new Maven project.
Some fields are prepared for my own use and integration in the http://keyboardplaying.org[Keyboard Playing] ecosystem but this may be easily modified.

== How to use?

[cols="1,2",options=""]
|===
| `pom-multimodule-parent-template.xml` | template for the parent of multimodule Maven project

| `pom-multimodule-child-template.xml`  | template to apply to each child of the multimodule project

| `pom-single-module-template.xml`      | template for simple, single-module Maven project
|===

== POM properties

=== Java version

Property:: `java.version`
Description:: the version of Java you are using
Default:: `1.7`

These templates were designed for Java 7 projects. If you wish to use another version, you should set the `java.version` property.

The maven-compiler-plugin uses two properties to determine which version the sources are coded in and which version they should be compiled to.
SonarQube also uses two different properties, but not the same.

These templates automatically copies the content of the `java.version` property to these other properties

* `java.version` -> `maven.compiler.source` -> `sonar.java.source`
* `java.version` -> `maven.compiler.target` -> `sonar.java.target`

=== File encoding

Property:: `project.build.sourceEncoding`
Description:: the encoding for your files
Default:: `UTF-8`

This is the default property used by all standard Maven project (compiler, jar, war, ...).

=== SCM information

The SCM information and many URLs are generated based on two properties you must override:

Github user::
  Property::: `github.user`
  Description::: the user the repository belongs to
  Default::: `cyChop`
Github repo::
  Property::: `github.repo`
  Description::: the name of the repository
  Default::: ` ${project.artifactId}`

Also, Maven will generate incorrect SCM information in modules. To avoid this, you should use the template I provide for child modules or copy this in your child POM:

[source,xml]
----
<scm>
  <url>https://github.com/${github.user}/${github.repo}</url>
  <connection>scm:git:https://github.com/${github.user}/${github.repo}.git</connection>
  <developerConnection>scm:git:git@github.com:${github.user}/${github.repo}.git</developerConnection>
</scm>
----

== Features

=== Continuous integration

==== Coverage report

The `<build/>` section contains plugin definitions required to use Coveralls.io reports with the Cobertura plugin.

===== Enabling coverage reports in Travis CI

Add the following to your `.travis.yml` configuration file:

----
after_success:
  - mvn cobertura:cobertura coveralls:report
----

==== Sonar

`sonar.java.source` and `sonar.java.target` are the Sonar equivalent of `maven.compiler.source` and `maven.compiler.target`. They are automatically set to the same value so that, if you use Sonar for static analysis, it will be performed with the same settings as your compilation.

=== Maven site

==== Reports

Some reports are automatically included inside the Maven-generated site (`mvn site`). These reports are:

* Surefire test report;
* Cobertura coverage report;
* API documentation.
